### ISSUE TITLE
16.3 Problems

### ISSUE THREAD

**Issue by D4D25A** [mineek/Serotonin#27]
Version 1.1 isn’t working on my iPhone 14 Pro 16.3. It let’s me jailbrek and userspace reboot but it doesn’t show the phone number text at the bottom and no tweaks work even when I try respringing.

Other people on 16.3 have also experienced this problem. 

Got it working with haxi0’s build instead: https://raw.githubusercontent.com/haxi0/Serotonin/A12restart/Serotonin.tipa

Perhaps libpatchfinder is causing this? Haxi0’s version has hardcoded offsets instead.

**Comment by PAINCLOWN** [comment]
+1

**Comment by jordanjosephc1502** [comment]
1+ on ios 16.2

**Comment by RazaviIoz** [comment]
+1!💙

**Comment by whoeevee** [comment]
+1 on ios 16.2

**Comment by z-ffqq** [comment]
bump, iPhone XR iOS 16.3.1

**Comment by jordanjosephc1502** [comment]
fixed my issue thank you so much

**Comment by hoanmaster321** [comment]
try again https://www.mediafire.com/file/h4b241pssv2ggsa/Serotonin.tipa/file

**Comment by camenling** [comment]
+1 14pm 16.2

**Comment by nyghtmyre** [comment]
> try again https://www.mediafire.com/file/h4b241pssv2ggsa/Serotonin.tipa/file

hey +1 this worked for me but im wondering where you got it from for further updates of serotonin? 13 16.3

**Comment by hoanmaster321** [comment]
> > try again https://www.mediafire.com/file/h4b241pssv2ggsa/Serotonin.tipa/file
> 
> hey +1 this worked for me but im wondering where you got it from for further updates of serotonin? 13 16.3

It is new ver 1.1 . It is origin + trick fix. I update ver new if dev push ver new

**Comment by dleovl** [comment]
> > > try again https://www.mediafire.com/file/h4b241pssv2ggsa/Serotonin.tipa/file
> > 
> > 
> > hey +1 this worked for me but im wondering where you got it from for further updates of serotonin? 13 16.3
> 
> It is new ver 1.1 . It is origin + trick fix. I update ver new if dev push ver new

Make a PR. Nobody can confirm if this link is legitimate or not.

**Comment by hoanmaster321** [comment]
> Make a PR. Nobody can confirm if this link is legitimate or not.

It is real or you stop download . Dev wating update

**Comment by Faex-an** [comment]
When i use the Hexi0's version i get that footnote but when i rebuild apps from bootstrap after restarting the server. the respring logo appears and it keeps on spinning and my device gets hot. The new version of Serotonin not even giving the footnote but i do get userreboot option, after the reboot there is no footnote or whatsoever. Help?

**Comment by Ecareee** [comment]
+1, finally working

**Comment by z-ffqq** [comment]
Fixed as of commit [9cb9ab0](https://github.com/mineek/Serotonin/commit/9cb9ab086607aaa70e8c44a3c3a0d547f79d5058).

**Comment by FinleyVickers** [comment]
Still does not work for me, iPhone 11, ios 16.3

**Comment by D4D25A** [comment]
> Still does not work for me, iPhone 11, ios 16.3

Try using the latest release on the official Serotonin GitHub page.

**Comment by FinleyVickers** [comment]
> > Still does not work for me, iPhone 11, ios 16.3
> 
> Try using the latest release on the official Serotonin GitHub page.

Tried it, still does not work for me. At least in the 5 times I've tried it.

**Comment by z-ffqq** [comment]
> > > Still does not work for me, iPhone 11, ios 16.3
> > 
> > 
> > Try using the latest release on the official Serotonin GitHub page.
> 
> Tried it, still does not work for me. At least in the 5 times I've tried it.

Keep trying, it took me 11 tries till I got it working. (16.3.1)
